
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>email.errors&#58; Exception and Defect Classes - Python 2.7 - W3cubDocs</title>
  
  <meta name="description" content=" The following exception classes are defined in the email.errors module&#58; ">
  <meta name="keywords" content="email, errors, exception, and, defect, classes, python, python~2.7">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/python~2.7/library/email.errors.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-e498cd0ebe8746846fec95b1a53ab3bb0fb7f47f794f0a38f44c98a1f0d03b21d777ae2c583732e44a5a890f6eacb79a5333545db9d5f3616091ba21ca17d916.css">
  <script src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js" type="text/javascript"></script>
  <script src="/json/python~2.7.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/python~2.7/" class="_nav-link" title="" style="margin-left:0;">Python 2.7</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _python">
				
				
<h1 id="email-errors-exception-and-defect-classes"> email.errors: Exception and Defect classes</h1> <p id="module-email.errors">The following exception classes are defined in the <a class="reference internal" href="#module-email.errors" title="email.errors: The exception classes used by the email package."><code>email.errors</code></a> module:</p> <dl class="exception"> <dt id="email.errors.MessageError">
<code>exception email.errors.MessageError</code> </dt> <dd>
<p>This is the base class for all exceptions that the <a class="reference internal" href="email#module-email" title="email: Package supporting the parsing, manipulating, and generating email messages, including MIME documents."><code>email</code></a> package can raise. It is derived from the standard <a class="reference internal" href="exceptions#exceptions.Exception" title="exceptions.Exception"><code>Exception</code></a> class and defines no additional methods.</p> </dd>
</dl> <dl class="exception"> <dt id="email.errors.MessageParseError">
<code>exception email.errors.MessageParseError</code> </dt> <dd>
<p>This is the base class for exceptions raised by the <a class="reference internal" href="email.parser#email.parser.Parser" title="email.parser.Parser"><code>Parser</code></a> class. It is derived from <a class="reference internal" href="#email.errors.MessageError" title="email.errors.MessageError"><code>MessageError</code></a>.</p> </dd>
</dl> <dl class="exception"> <dt id="email.errors.HeaderParseError">
<code>exception email.errors.HeaderParseError</code> </dt> <dd>
<p>Raised under some error conditions when parsing the <a class="rfc reference external" href="https://tools.ietf.org/html/rfc2822.html" id="index-0"><strong>RFC 2822</strong></a> headers of a message, this class is derived from <a class="reference internal" href="#email.errors.MessageParseError" title="email.errors.MessageParseError"><code>MessageParseError</code></a>. It can be raised from the <a class="reference internal" href="email.parser#email.parser.Parser.parse" title="email.parser.Parser.parse"><code>Parser.parse</code></a> or <a class="reference internal" href="email.parser#email.parser.Parser.parsestr" title="email.parser.Parser.parsestr"><code>Parser.parsestr</code></a> methods.</p> <p>Situations where it can be raised include finding an envelope header after the first <a class="rfc reference external" href="https://tools.ietf.org/html/rfc2822.html" id="index-1"><strong>RFC 2822</strong></a> header of the message, finding a continuation line before the first <a class="rfc reference external" href="https://tools.ietf.org/html/rfc2822.html" id="index-2"><strong>RFC 2822</strong></a> header is found, or finding a line in the headers which is neither a header or a continuation line.</p> </dd>
</dl> <dl class="exception"> <dt id="email.errors.BoundaryError">
<code>exception email.errors.BoundaryError</code> </dt> <dd>
<p>Raised under some error conditions when parsing the <a class="rfc reference external" href="https://tools.ietf.org/html/rfc2822.html" id="index-3"><strong>RFC 2822</strong></a> headers of a message, this class is derived from <a class="reference internal" href="#email.errors.MessageParseError" title="email.errors.MessageParseError"><code>MessageParseError</code></a>. It can be raised from the <a class="reference internal" href="email.parser#email.parser.Parser.parse" title="email.parser.Parser.parse"><code>Parser.parse</code></a> or <a class="reference internal" href="email.parser#email.parser.Parser.parsestr" title="email.parser.Parser.parsestr"><code>Parser.parsestr</code></a> methods.</p> <p>Situations where it can be raised include not being able to find the starting or terminating boundary in a <em class="mimetype">multipart/*</em> message when strict parsing is used.</p> </dd>
</dl> <dl class="exception"> <dt id="email.errors.MultipartConversionError">
<code>exception email.errors.MultipartConversionError</code> </dt> <dd>
<p>Raised when a payload is added to a <a class="reference internal" href="email.message#email.message.Message" title="email.message.Message"><code>Message</code></a> object using <code>add_payload()</code>, but the payload is already a scalar and the message’s <em class="mailheader">Content-Type</em> main type is not either <em class="mimetype">multipart</em> or missing. <a class="reference internal" href="#email.errors.MultipartConversionError" title="email.errors.MultipartConversionError"><code>MultipartConversionError</code></a> multiply inherits from <a class="reference internal" href="#email.errors.MessageError" title="email.errors.MessageError"><code>MessageError</code></a> and the built-in <a class="reference internal" href="exceptions#exceptions.TypeError" title="exceptions.TypeError"><code>TypeError</code></a>.</p> <p>Since <code>Message.add_payload()</code> is deprecated, this exception is rarely raised in practice. However the exception may also be raised if the <a class="reference internal" href="email.message#email.message.Message.attach" title="email.message.Message.attach"><code>attach()</code></a> method is called on an instance of a class derived from <a class="reference internal" href="email.mime#email.mime.nonmultipart.MIMENonMultipart" title="email.mime.nonmultipart.MIMENonMultipart"><code>MIMENonMultipart</code></a> (e.g. <a class="reference internal" href="email.mime#email.mime.image.MIMEImage" title="email.mime.image.MIMEImage"><code>MIMEImage</code></a>).</p> </dd>
</dl> <p>Here’s the list of the defects that the <a class="reference internal" href="email.parser#email.parser.FeedParser" title="email.parser.FeedParser"><code>FeedParser</code></a> can find while parsing messages. Note that the defects are added to the message where the problem was found, so for example, if a message nested inside a <em class="mimetype">multipart/alternative</em> had a malformed header, that nested message object would have a defect, but the containing messages would not.</p> <p>All defect classes are subclassed from <code>email.errors.MessageDefect</code>, but this class is <em>not</em> an exception!</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.4: </span>All the defect classes were added.</p> </div> <ul class="simple"> <li>
<code>NoBoundaryInMultipartDefect</code> – A message claimed to be a multipart, but had no <em class="mimetype">boundary</em> parameter.</li> <li>
<code>StartBoundaryNotFoundDefect</code> – The start boundary claimed in the <em class="mailheader">Content-Type</em> header was never found.</li> <li>
<code>FirstHeaderLineIsContinuationDefect</code> – The message had a continuation line as its first header line.</li> <li>
<code>MisplacedEnvelopeHeaderDefect</code> - A “Unix From” header was found in the middle of a header block.</li> <li>
<code>MalformedHeaderDefect</code> – A header was found that was missing a colon, or was otherwise malformed.</li> <li>
<code>MultipartInvariantViolationDefect</code> – A message claimed to be a <em class="mimetype">multipart</em>, but no subparts were found. Note that when a message has this defect, its <a class="reference internal" href="email.message#email.message.Message.is_multipart" title="email.message.Message.is_multipart"><code>is_multipart()</code></a> method may return false even though its content type claims to be <em class="mimetype">multipart</em>.</li> </ul>
<div class="_attribution">
  <p class="_attribution-p">
    © 2001–2020 Python Software Foundation<br>Licensed under the PSF License.<br>
    <a href="https://docs.python.org/2.7/library/email.errors.html" class="_attribution-link">https://docs.python.org/2.7/library/email.errors.html</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
