
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>CertPathValidatorException - OpenJDK 11 - W3cubDocs</title>
  
  <meta name="description" content=" An exception indicating one of a variety of problems encountered when validating a certification path. ">
  <meta name="keywords" content="class, certpathvalidatorexception, openjdk, openjdk~11">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/openjdk~11/java.base/java/security/cert/certpathvalidatorexception.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-01fda2ddb8339756caccf7add5ad4cf849ab52d069bd799015c7f04f93164f64753bff0d15a49d8060b1e66e41002bb301ccadc2350937df079cea3cd52d3cca.css">
  <script src="/assets/application-d9be6f56a823612443fc15b2e027a630e02c4ad2685bb750d13fa4fae28d46c3e7f7ebb69bd4bafddf116f218f9372e9be44021d4247dc20424e2fd1ff8cef81.js" type="text/javascript"></script>
  <script src="/json/openjdk~11.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script data-ad-client="ca-pub-2572770204602497" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/openjdk~11/" class="_nav-link" title="" style="margin-left:0;">OpenJDK 11</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="link"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _openjdk">
				
				
<main role="main">    <h1>Class CertPathValidatorException</h1>   <ul class="inheritance"> <li><a href="../../lang/object">java.lang.Object</a></li> <li> <ul class="inheritance"> <li><a href="../../lang/throwable">java.lang.Throwable</a></li> <li> <ul class="inheritance"> <li><a href="../../lang/exception">java.lang.Exception</a></li> <li> <ul class="inheritance"> <li><a href="../generalsecurityexception">java.security.GeneralSecurityException</a></li> <li> <ul class="inheritance"> <li>java.security.cert.CertPathValidatorException</li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul>   <dl> <dt>All Implemented Interfaces:</dt> <dd><code><a href="../../io/serializable">Serializable</a></code></dd> </dl>  <pre data-language="java">public class CertPathValidatorException
extends GeneralSecurityException</pre> <div>
<p>An exception indicating one of a variety of problems encountered when validating a certification path. </p>
<p> A <code>CertPathValidatorException</code> provides support for wrapping exceptions. The <a href="../../lang/throwable#getCause()"><code>getCause</code></a> method returns the throwable, if any, that caused this exception to be thrown. </p>
<p> A <code>CertPathValidatorException</code> may also include the certification path that was being validated when the exception was thrown, the index of the certificate in the certification path that caused the exception to be thrown, and the reason that caused the failure. Use the <a href="#getCertPath()"><code>getCertPath</code></a>, <a href="#getIndex()"><code>getIndex</code></a>, and <a href="#getReason()"><code>getReason</code></a> methods to retrieve this information. </p>
<p> <b>Concurrent Access</b> </p>
<p> Unless otherwise specified, the methods defined in this class are not thread-safe. Multiple threads that need to access a single object concurrently should synchronize amongst themselves and provide the necessary locking. Multiple threads each manipulating separate objects need not synchronize.</p>
</div> <dl> <dt>Since:</dt> <dd>1.4</dd> <dt>See Also:</dt> <dd>
<a href="certpathvalidator"><code>CertPathValidator</code></a>, <a href="https://docs.oracle.com/en/java/javase/11/docs/api/serialized-form.html#java.security.cert.CertPathValidatorException">Serialized Form</a>
</dd> </dl>      <section role="region">  <h2>Nested Class Summary</h2> <table> <caption>Nested Classes </caption> <tr> <th scope="col">Modifier and Type</th> <th scope="col">Class</th> <th scope="col">Description</th> </tr> <tr> <td><code>static class </code></td> <th scope="row"><code><a href="certpathvalidatorexception.basicreason">CertPathValidatorException.BasicReason</a></code></th> <td> <p>The BasicReason enumerates the potential reasons that a certification path of any type may be invalid.</p> </td> </tr> <tr> <td><code>static interface </code></td> <th scope="row"><code><a href="certpathvalidatorexception.reason">CertPathValidatorException.Reason</a></code></th> <td> <p>The reason the validation algorithm failed.</p> </td> </tr> </table>  </section>  <section role="region">  <h2>Constructor Summary</h2> <table> <caption>Constructors </caption> <tr> <th scope="col">Constructor</th> <th scope="col">Description</th> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E()">CertPathValidatorException</a>()</code></th> <td> <p>Creates a <code>CertPathValidatorException</code> with no detail message.</p> </td> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E(java.lang.String)">CertPathValidatorException</a>​(<a href="../../lang/string">String</a> msg)</code></th> <td> <p>Creates a <code>CertPathValidatorException</code> with the given detail message.</p> </td> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E(java.lang.String,java.lang.Throwable)">CertPathValidatorException</a>​(<a href="../../lang/string">String</a> msg,
                          <a href="../../lang/throwable">Throwable</a> cause)</code></th> <td> <p>Creates a <code>CertPathValidatorException</code> with the specified detail message and cause.</p> </td> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E(java.lang.String,java.lang.Throwable,java.security.cert.CertPath,int)">CertPathValidatorException</a>​(<a href="../../lang/string">String</a> msg,
                          <a href="../../lang/throwable">Throwable</a> cause,
                          <a href="certpath">CertPath</a> certPath,
                          int index)</code></th> <td> <p>Creates a <code>CertPathValidatorException</code> with the specified detail message, cause, certification path, and index.</p> </td> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E(java.lang.String,java.lang.Throwable,java.security.cert.CertPath,int,java.security.cert.CertPathValidatorException.Reason)">CertPathValidatorException</a>​(<a href="../../lang/string">String</a> msg,
                          <a href="../../lang/throwable">Throwable</a> cause,
                          <a href="certpath">CertPath</a> certPath,
                          int index,
                          <a href="certpathvalidatorexception.reason">CertPathValidatorException.Reason</a> reason)</code></th> <td> <p>Creates a <code>CertPathValidatorException</code> with the specified detail message, cause, certification path, index, and reason.</p> </td> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E(java.lang.Throwable)">CertPathValidatorException</a>​(<a href="../../lang/throwable">Throwable</a> cause)</code></th> <td> <p>Creates a <code>CertPathValidatorException</code> that wraps the specified throwable.</p> </td> </tr> </table>  </section>  <section role="region">  <h2>Method Summary</h2> <table> <caption>All Methods <a href="javascript:show(2);">Instance Methods</a> <a href="javascript:show(8);">Concrete Methods</a> </caption> <tr> <th scope="col">Modifier and Type</th> <th scope="col">Method</th> <th scope="col">Description</th> </tr> <tr id="i0"> <td><code><a href="certpath">CertPath</a></code></td> <th scope="row"><code><a href="#getCertPath()">getCertPath</a>()</code></th> <td> <p>Returns the certification path that was being validated when the exception was thrown.</p> </td> </tr> <tr id="i1"> <td><code>int</code></td> <th scope="row"><code><a href="#getIndex()">getIndex</a>()</code></th> <td> <p>Returns the index of the certificate in the certification path that caused the exception to be thrown.</p> </td> </tr> <tr id="i2"> <td><code><a href="certpathvalidatorexception.reason">CertPathValidatorException.Reason</a></code></td> <th scope="row"><code><a href="#getReason()">getReason</a>()</code></th> <td> <p>Returns the reason that the validation failed.</p> </td> </tr> </table>  <h2>Methods declared in class java.lang.<a href="../../lang/throwable">Throwable</a>
</h2> <code><a href="../../lang/throwable#addSuppressed(java.lang.Throwable)">addSuppressed</a>, <a href="../../lang/throwable#fillInStackTrace()">fillInStackTrace</a>, <a href="../../lang/throwable#getCause()">getCause</a>, <a href="../../lang/throwable#getLocalizedMessage()">getLocalizedMessage</a>, <a href="../../lang/throwable#getMessage()">getMessage</a>, <a href="../../lang/throwable#getStackTrace()">getStackTrace</a>, <a href="../../lang/throwable#getSuppressed()">getSuppressed</a>, <a href="../../lang/throwable#initCause(java.lang.Throwable)">initCause</a>, <a href="../../lang/throwable#printStackTrace()">printStackTrace</a>, <a href="../../lang/throwable#printStackTrace(java.io.PrintStream)">printStackTrace</a>, <a href="../../lang/throwable#printStackTrace(java.io.PrintWriter)">printStackTrace</a>, <a href="../../lang/throwable#setStackTrace(java.lang.StackTraceElement%5B%5D)">setStackTrace</a>, <a href="../../lang/throwable#toString()">toString</a></code>  <h2>Methods declared in class java.lang.<a href="../../lang/object">Object</a>
</h2> <code><a href="../../lang/object#clone()">clone</a>, <a href="../../lang/object#equals(java.lang.Object)">equals</a>, <a href="../../lang/object#finalize()">finalize</a>, <a href="../../lang/object#getClass()">getClass</a>, <a href="../../lang/object#hashCode()">hashCode</a>, <a href="../../lang/object#notify()">notify</a>, <a href="../../lang/object#notifyAll()">notifyAll</a>, <a href="../../lang/object#wait()">wait</a>, <a href="../../lang/object#wait(long)">wait</a>, <a href="../../lang/object#wait(long,int)">wait</a></code>  </section>   <div>   <section role="region">  <h2>Constructor Detail</h2>   <h3>CertPathValidatorException</h3> <pre data-language="java">public CertPathValidatorException()</pre> <p>Creates a <code>CertPathValidatorException</code> with no detail message.</p>    <h3>CertPathValidatorException</h3> <pre data-language="java">public CertPathValidatorException​(String msg)</pre> <p>Creates a <code>CertPathValidatorException</code> with the given detail message. A detail message is a <code>String</code> that describes this particular exception.</p> <dl> <dt>Parameters:</dt> <dd>
<code>msg</code> - the detail message</dd> </dl>    <h3>CertPathValidatorException</h3> <pre data-language="java">public CertPathValidatorException​(Throwable cause)</pre> <p>Creates a <code>CertPathValidatorException</code> that wraps the specified throwable. This allows any exception to be converted into a <code>CertPathValidatorException</code>, while retaining information about the wrapped exception, which may be useful for debugging. The detail message is set to (<code>cause==null ? null : cause.toString()</code>) (which typically contains the class and detail message of cause).</p> <dl> <dt>Parameters:</dt> <dd>
<code>cause</code> - the cause (which is saved for later retrieval by the <a href="../../lang/throwable#getCause()"><code>getCause()</code></a> method). (A <code>null</code> value is permitted, and indicates that the cause is nonexistent or unknown.)</dd> </dl>    <h3>CertPathValidatorException</h3> <pre data-language="java">public CertPathValidatorException​(String msg,
                                  Throwable cause)</pre> <p>Creates a <code>CertPathValidatorException</code> with the specified detail message and cause.</p> <dl> <dt>Parameters:</dt> <dd>
<code>msg</code> - the detail message</dd> <dd>
<code>cause</code> - the cause (which is saved for later retrieval by the <a href="../../lang/throwable#getCause()"><code>getCause()</code></a> method). (A <code>null</code> value is permitted, and indicates that the cause is nonexistent or unknown.)</dd> </dl>    <h3>CertPathValidatorException</h3> <pre data-language="java">public CertPathValidatorException​(String msg,
                                  Throwable cause,
                                  CertPath certPath,
                                  int index)</pre> <p>Creates a <code>CertPathValidatorException</code> with the specified detail message, cause, certification path, and index.</p> <dl> <dt>Parameters:</dt> <dd>
<code>msg</code> - the detail message (or <code>null</code> if none)</dd> <dd>
<code>cause</code> - the cause (or <code>null</code> if none)</dd> <dd>
<code>certPath</code> - the certification path that was in the process of being validated when the error was encountered</dd> <dd>
<code>index</code> - the index of the certificate in the certification path that caused the error (or -1 if not applicable). Note that the list of certificates in a <code>CertPath</code> is zero based.</dd> <dt>Throws:</dt> <dd>
<code><a href="../../lang/indexoutofboundsexception">IndexOutOfBoundsException</a></code> - if the index is out of range <code>(index &lt; -1 || (certPath != null &amp;&amp; index &gt;=
 certPath.getCertificates().size()) </code>
</dd> <dd>
<code><a href="../../lang/illegalargumentexception">IllegalArgumentException</a></code> - if <code>certPath</code> is <code>null</code> and <code>index</code> is not -1</dd> </dl>    <h3>CertPathValidatorException</h3> <pre data-language="java">public CertPathValidatorException​(String msg,
                                  Throwable cause,
                                  CertPath certPath,
                                  int index,
                                  CertPathValidatorException.Reason reason)</pre> <p>Creates a <code>CertPathValidatorException</code> with the specified detail message, cause, certification path, index, and reason.</p> <dl> <dt>Parameters:</dt> <dd>
<code>msg</code> - the detail message (or <code>null</code> if none)</dd> <dd>
<code>cause</code> - the cause (or <code>null</code> if none)</dd> <dd>
<code>certPath</code> - the certification path that was in the process of being validated when the error was encountered</dd> <dd>
<code>index</code> - the index of the certificate in the certification path that caused the error (or -1 if not applicable). Note that the list of certificates in a <code>CertPath</code> is zero based.</dd> <dd>
<code>reason</code> - the reason the validation failed</dd> <dt>Throws:</dt> <dd>
<code><a href="../../lang/indexoutofboundsexception">IndexOutOfBoundsException</a></code> - if the index is out of range <code>(index &lt; -1 || (certPath != null &amp;&amp; index &gt;=
 certPath.getCertificates().size()) </code>
</dd> <dd>
<code><a href="../../lang/illegalargumentexception">IllegalArgumentException</a></code> - if <code>certPath</code> is <code>null</code> and <code>index</code> is not -1</dd> <dd>
<code><a href="../../lang/nullpointerexception">NullPointerException</a></code> - if <code>reason</code> is <code>null</code>
</dd> <dt>Since:</dt> <dd>1.7</dd> </dl>   </section>  <section role="region">  <h2>Method Detail</h2>   <h3>getCertPath</h3> <pre data-language="java">public CertPath getCertPath()</pre> <p>Returns the certification path that was being validated when the exception was thrown.</p> <dl> <dt>Returns:</dt> <dd>the <code>CertPath</code> that was being validated when the exception was thrown (or <code>null</code> if not specified)</dd> </dl>    <h3>getIndex</h3> <pre data-language="java">public int getIndex()</pre> <p>Returns the index of the certificate in the certification path that caused the exception to be thrown. Note that the list of certificates in a <code>CertPath</code> is zero based. If no index has been set, -1 is returned.</p> <dl> <dt>Returns:</dt> <dd>the index that has been set, or -1 if none has been set</dd> </dl>    <h3>getReason</h3> <pre data-language="java">public CertPathValidatorException.Reason getReason()</pre> <p>Returns the reason that the validation failed. The reason is associated with the index of the certificate returned by <a href="#getIndex()"><code>getIndex()</code></a>.</p> <dl> <dt>Returns:</dt> <dd>the reason that the validation failed, or <code>BasicReason.UNSPECIFIED</code> if a reason has not been specified</dd> <dt>Since:</dt> <dd>1.7</dd> </dl>   </section>  </div>  </main>  <div class="_attribution">
  <p class="_attribution-p">
    © 1993, 2020, Oracle and/or its affiliates. All rights reserved.<br>Documentation extracted from Debian's OpenJDK Development Kit package.<br>Licensed under the GNU General Public License, version 2, with the Classpath Exception.<br>Various third party code in OpenJDK is licensed under different licenses (see Debian package).<br>Java and OpenJDK are trademarks or registered trademarks of Oracle and/or its affiliates.<br>
    <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/cert/CertPathValidatorException.html" class="_attribution-link">https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/cert/CertPathValidatorException.html</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
