
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Application Errors - Flask 1.1 - W3cubDocs</title>
  
  <meta name="description" content=" New in version 0.3. ">
  <meta name="keywords" content="application, errors, flask, flask~1.1">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/flask~1.1/errorhandling/">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-c7076d7cdaddc6969cb97911f9b488459d4bebca88d6f2525f2a12432f0bec8426c751ccfbc34920dda3867e50ab24698396bc4e548e788fc826f69a158d6856.css">
  <script src="/assets/application-d9be6f56a823612443fc15b2e027a630e02c4ad2685bb750d13fa4fae28d46c3e7f7ebb69bd4bafddf116f218f9372e9be44021d4247dc20424e2fd1ff8cef81.js" type="text/javascript"></script>
  <script src="/json/flask~1.1.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script data-ad-client="ca-pub-2572770204602497" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/flask~1.1/" class="_nav-link" title="" style="margin-left:0;">Flask 1.1</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="link"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _sphinx">
				
				
<h1 id="id1">Application Errors</h1> <details class="changelog"> <summary>Changelog</summary><div class="versionadded"> <p><span class="versionmodified added">New in version 0.3.</span></p> </div> </details><p>Applications fail, servers fail. Sooner or later you will see an exception in production. Even if your code is 100% correct, you will still see exceptions from time to time. Why? Because everything else involved will fail. Here are some situations where perfectly fine code can lead to server errors:</p> <ul class="simple"> <li>the client terminated the request early and the application was still reading from the incoming data</li> <li>the database server was overloaded and could not handle the query</li> <li>a filesystem is full</li> <li>a harddrive crashed</li> <li>a backend server overloaded</li> <li>a programming error in a library you are using</li> <li>network connection of the server to another system failed</li> </ul> <p>And that’s just a small sample of issues you could be facing. So how do we deal with that sort of problem? By default if your application runs in production mode, Flask will display a very simple page for you and log the exception to the <a class="reference internal" href="../api/index#flask.Flask.logger" title="flask.Flask.logger"><code>logger</code></a>.</p> <p>But there is more you can do, and we will cover some better setups to deal with errors.</p>  <h2 id="error-logging-tools">Error Logging Tools</h2> <p>Sending error mails, even if just for critical ones, can become overwhelming if enough users are hitting the error and log files are typically never looked at. This is why we recommend using <a class="reference external" href="https://sentry.io/">Sentry</a> for dealing with application errors. It’s available as an Open Source project <a class="reference external" href="https://github.com/getsentry/sentry">on GitHub</a> and is also available as a <a class="reference external" href="https://sentry.io/signup/">hosted version</a> which you can try for free. Sentry aggregates duplicate errors, captures the full stack trace and local variables for debugging, and sends you mails based on new errors or frequency thresholds.</p> <p>To use Sentry you need to install the <code>sentry-sdk</code> client with extra <code>flask</code> dependencies:</p> <pre data-language="python">$ pip install sentry-sdk[flask]
</pre> <p>And then add this to your Flask app:</p> <pre data-language="python">import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init('YOUR_DSN_HERE',integrations=[FlaskIntegration()])
</pre> <p>The <code>YOUR_DSN_HERE</code> value needs to be replaced with the DSN value you get from your Sentry installation.</p> <p>After installation, failures leading to an Internal Server Error are automatically reported to Sentry and from there you can receive error notifications.</p> <p>Follow-up reads:</p> <ul class="simple"> <li>Sentry also supports catching errors from your worker queue (RQ, Celery) in a similar fashion. See the <a class="reference external" href="https://docs.sentry.io/platforms/python/">Python SDK docs</a> for more information.</li> <li><a class="reference external" href="https://docs.sentry.io/quickstart/?platform=python">Getting started with Sentry</a></li> <li>
<a class="reference external" href="https://docs.sentry.io/platforms/python/guides/flask/">Flask-specific documentation</a>.</li> </ul>   <h2 id="id2">Error handlers</h2> <p id="error-handlers">You might want to show custom error pages to the user when an error occurs. This can be done by registering error handlers.</p> <p>An error handler is a normal view function that returns a response, but instead of being registered for a route, it is registered for an exception or HTTP status code that would be raised while trying to handle a request.</p>  <h3 id="registering">Registering</h3> <p>Register handlers by decorating a function with <a class="reference internal" href="../api/index#flask.Flask.errorhandler" title="flask.Flask.errorhandler"><code>errorhandler()</code></a>. Or use <a class="reference internal" href="../api/index#flask.Flask.register_error_handler" title="flask.Flask.register_error_handler"><code>register_error_handler()</code></a> to register the function later. Remember to set the error code when returning the response.</p> <pre data-language="python">@app.errorhandler(werkzeug.exceptions.BadRequest)
def handle_bad_request(e):
    return 'bad request!', 400

# or, without the decorator
app.register_error_handler(400, handle_bad_request)
</pre> <p><a class="reference external" href="https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/#werkzeug.exceptions.HTTPException" title="(in Werkzeug v1.0.x)"><code>werkzeug.exceptions.HTTPException</code></a> subclasses like <a class="reference external" href="https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/#werkzeug.exceptions.BadRequest" title="(in Werkzeug v1.0.x)"><code>BadRequest</code></a> and their HTTP codes are interchangeable when registering handlers. (<code>BadRequest.code == 400</code>)</p> <p>Non-standard HTTP codes cannot be registered by code because they are not known by Werkzeug. Instead, define a subclass of <a class="reference external" href="https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/#werkzeug.exceptions.HTTPException" title="(in Werkzeug v1.0.x)"><code>HTTPException</code></a> with the appropriate code and register and raise that exception class.</p> <pre data-language="python">class InsufficientStorage(werkzeug.exceptions.HTTPException):
    code = 507
    description = 'Not enough storage space.'

app.register_error_handler(InsufficientStorage, handle_507)

raise InsufficientStorage()
</pre> <p>Handlers can be registered for any exception class, not just <a class="reference external" href="https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/#werkzeug.exceptions.HTTPException" title="(in Werkzeug v1.0.x)"><code>HTTPException</code></a> subclasses or HTTP status codes. Handlers can be registered for a specific class, or for all subclasses of a parent class.</p>   <h3 id="handling">Handling</h3> <p>When an exception is caught by Flask while handling a request, it is first looked up by code. If no handler is registered for the code, it is looked up by its class hierarchy; the most specific handler is chosen. If no handler is registered, <a class="reference external" href="https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/#werkzeug.exceptions.HTTPException" title="(in Werkzeug v1.0.x)"><code>HTTPException</code></a> subclasses show a generic message about their code, while other exceptions are converted to a generic 500 Internal Server Error.</p> <p>For example, if an instance of <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#ConnectionRefusedError" title="(in Python v3.9)"><code>ConnectionRefusedError</code></a> is raised, and a handler is registered for <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#ConnectionError" title="(in Python v3.9)"><code>ConnectionError</code></a> and <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#ConnectionRefusedError" title="(in Python v3.9)"><code>ConnectionRefusedError</code></a>, the more specific <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#ConnectionRefusedError" title="(in Python v3.9)"><code>ConnectionRefusedError</code></a> handler is called with the exception instance to generate the response.</p> <p>Handlers registered on the blueprint take precedence over those registered globally on the application, assuming a blueprint is handling the request that raises the exception. However, the blueprint cannot handle 404 routing errors because the 404 occurs at the routing level before the blueprint can be determined.</p>   <h3 id="generic-exception-handlers">Generic Exception Handlers</h3> <p>It is possible to register error handlers for very generic base classes such as <code>HTTPException</code> or even <code>Exception</code>. However, be aware that these will catch more than you might expect.</p> <p>An error handler for <code>HTTPException</code> might be useful for turning the default HTML errors pages into JSON, for example. However, this handler will trigger for things you don’t cause directly, such as 404 and 405 errors during routing. Be sure to craft your handler carefully so you don’t lose information about the HTTP error.</p> <pre data-language="python">from flask import json
from werkzeug.exceptions import HTTPException

@app.errorhandler(HTTPException)
def handle_exception(e):
    """Return JSON instead of HTML for HTTP errors."""
    # start with the correct headers and status code from the error
    response = e.get_response()
    # replace the body with JSON
    response.data = json.dumps({
        "code": e.code,
        "name": e.name,
        "description": e.description,
    })
    response.content_type = "application/json"
    return response
</pre> <p>An error handler for <code>Exception</code> might seem useful for changing how all errors, even unhandled ones, are presented to the user. However, this is similar to doing <code>except Exception:</code> in Python, it will capture <em>all</em> otherwise unhandled errors, including all HTTP status codes. In most cases it will be safer to register handlers for more specific exceptions. Since <code>HTTPException</code> instances are valid WSGI responses, you could also pass them through directly.</p> <pre data-language="python">from werkzeug.exceptions import HTTPException

@app.errorhandler(Exception)
def handle_exception(e):
    # pass through HTTP errors
    if isinstance(e, HTTPException):
        return e

    # now you're handling non-HTTP exceptions only
    return render_template("500_generic.html", e=e), 500
</pre> <p>Error handlers still respect the exception class hierarchy. If you register handlers for both <code>HTTPException</code> and <code>Exception</code>, the <code>Exception</code> handler will not handle <code>HTTPException</code> subclasses because it the <code>HTTPException</code> handler is more specific.</p>   <h3 id="unhandled-exceptions">Unhandled Exceptions</h3> <p>When there is no error handler registered for an exception, a 500 Internal Server Error will be returned instead. See <a class="reference internal" href="../api/index#flask.Flask.handle_exception" title="flask.Flask.handle_exception"><code>flask.Flask.handle_exception()</code></a> for information about this behavior.</p> <p>If there is an error handler registered for <code>InternalServerError</code>, this will be invoked. As of Flask 1.1.0, this error handler will always be passed an instance of <code>InternalServerError</code>, not the original unhandled error. The original error is available as <code>e.original_exception</code>. Until Werkzeug 1.0.0, this attribute will only exist during unhandled errors, use <code>getattr</code> to get access it for compatibility.</p> <pre data-language="python">@app.errorhandler(InternalServerError)
def handle_500(e):
    original = getattr(e, "original_exception", None)

    if original is None:
        # direct 500 error, such as abort(500)
        return render_template("500.html"), 500

    # wrapped unhandled error
    return render_template("500_unhandled.html", e=original), 500
</pre>    <h2 id="logging">Logging</h2> <p>See <a class="reference internal" href="../logging/index"><span class="doc">Logging</span></a> for information on how to log exceptions, such as by emailing them to admins.</p>
<div class="_attribution">
  <p class="_attribution-p">
    © 2007–2020 Pallets<br>Licensed under the BSD 3-clause License.<br>
    <a href="https://flask.palletsprojects.com/en/1.1.x/errorhandling/" class="_attribution-link">https://flask.palletsprojects.com/en/1.1.x/errorhandling/</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
